name: jiva

include:
  - ./compose/minio/service.yml
  - ./compose/nginx/service.yml
  - ./compose/postgres/service.yml

services: {}

volumes:
  postgres_data:
    driver: local
  minio_data:
    driver: local

networks:
  jiva-network:
    driver: bridge
